
services:
  ###> symfony/application ###
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw
      - ./var:/var/www/html/var:rw
    env_file:
      - ./.env.local
    depends_on:
      database:
        condition: service_healthy
  messenger-worker:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw
      - ./var:/var/www/html/var:rw
    env_file:
      - ./.env.local
    depends_on:
      database:
        condition: service_healthy
    command: ["php", "bin/console", "messenger:consume", "async", "-vv"]
  ###< symfony/application ###

  ###> symfony/nginx ###
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  ###< symfony/nginx ###

  ###> symfony/doctrine ###
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=leveling
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "leveling", "-U", "admin"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< symfony/doctrine ###

volumes:
  ###> symfony/doctrine ###
  database_data:
###< symfony/doctrine ###
